# Inspect Panel Metadata

In [15]:
import pandas as pd
import csv
from pathlib import Path

## List Panel Files

In [16]:
panel_path = "U:/cdbui/MPE_Cytof/Metadata"

In [17]:
files = list(Path(panel_path).iterdir())

In [18]:
files

[WindowsPath('U:/cdbui/MPE_Cytof/Metadata/Cytokines_markers_022625.txt'),
 WindowsPath('U:/cdbui/MPE_Cytof/Metadata/mpe_cytof_sampleInfo_022625.txt'),
 WindowsPath('U:/cdbui/MPE_Cytof/Metadata/Myeloid_markers_022625.txt'),
 WindowsPath('U:/cdbui/MPE_Cytof/Metadata/TBNK_markers_022625.txt')]

## Read Panel Files

In [23]:
df_tbnk = pd.read_csv('U:/cdbui/MPE_Cytof/Metadata/TBNK_markers_022625.txt', sep='\t')
df_myeloid = pd.read_csv('U:/cdbui/MPE_Cytof/Metadata/Myeloid_markers_022625.txt', sep='\t')
df_cytokine = pd.read_csv('U:/cdbui/MPE_Cytof/Metadata/Cytokines_markers_022625.txt', sep='\t')

In [27]:
# view first few rows
display(df_tbnk.head(3))
display(df_myeloid.head(3))
display(df_cytokine.head(3))

  fcs_colname           fcs_desc      antigen Symbol marker_class
0       Y89Di          89Y_VISTA        VISTA   VSIR     function
1     Cd106Di         106Cd_CD27         CD27   CD27      lineage
2     Cd110Di  110Cd_CD336_NKp44  CD336_NKp44   NCR2      lineage

  fcs_colname    fcs_desc antigen Symbol marker_class
0       Y89Di    89Y_CD70    CD70   CD70      lineage
1     Cd106Di  106Cd_CD14    CD14   CD14      lineage
2     Cd110Di  110Cd_CD34    CD34   CD34      lineage

  fcs_colname        fcs_desc     antigen Symbol marker_class
0       Y89Di  89Y_CXCL1_GROA  CXCL1_GROA  CXCL1     function
1     Cd110Di      110Cd_CD34        CD34   CD34      lineage
2     Cd111Di       111Cd_CD4         CD4    CD4      lineage

In [41]:
df_tbnk

   fcs_colname            fcs_desc       antigen    Symbol      marker_class
0        Y89Di           89Y_VISTA         VISTA      VSIR          function
1      Cd106Di          106Cd_CD27          CD27      CD27           lineage
2      Cd110Di   110Cd_CD336_NKp44   CD336_NKp44      NCR2           lineage
3      Cd111Di           111Cd_CD4           CD4       CD4           lineage
4      Cd114Di          114Cd_CD70          CD70      CD70           lineage
5      In115Di          115In_CD57          CD57    B3GAT1           lineage
6      Cd116Di  116Cd_CD159C_NKG2C  CD159C_NKG2C     KLRC2           lineage
7      Pr141Di    141Pr_CD196_CCR6    CD196_CCR6      CCR6           lineage
8      Nd142Di   142Nd_CD183_CXCR3   CD183_CXCR3     CXCR3           lineage
9      Nd143Di    143Nd_CD357_GITR    CD357_GITR  TNFRSF18          function
10     Nd144Di          144Nd_CD69          CD69      CD69           lineage
11     Nd145Di          145Nd_CD94          CD94     KLRD1           lineage
12     Nd146Di         146Nd_CD161         CD161     KLRB1           lineage
13     Nd148Di          148Nd_CD16          CD16    FCGR3A           lineage
14     Sm149Di     149Sm_CD25_IL2R     CD25_IL2R     IL2RA          function
15     Nd150Di    150Nd_CD223_LAG3    CD223_LAG3      LAG3          function
16     Eu151Di    151Eu_CD137_41BB    CD137_41BB   TNFRSF9          function
17     Sm152Di         152Sm_TCRgd         TCRgd   TRG_TRD          function
18     Eu153Di   153Eu_CD185_CXCR5   CD185_CXCR5     CXCR5           lineage
19     Sm154Di        154Sm_CD45RO        CD45RO    CD45RO           lineage
20     Gd155Di        155Gd_CD45RA        CD45RA    CD45RA           lineage
21     Gd156Di    156Gd_CD274_PDL1    CD274_PDL1     CD274          function
22     Gd158Di          158Gd_CD39          CD39    ENTPD1          function
23     Tb159Di    159Tb_CD197_CCR7    CD197_CCR7      CCR7           lineage
24     Dy161Di          161Dy_TBET          TBET     TBX21          function
25     Dy162Di         162Dy_FOXP3         FOXP3     FOXP3          function
26     Dy163Di          163Dy_CD56          CD56     NCAM1           lineage
27     Dy164Di    164Dy_CD278_ICOS    CD278_ICOS      ICOS  lineage_function
28     Ho165Di          165Ho_CD19          CD19      CD19           lineage
29     Er166Di          166Er_CD28          CD28      CD28  lineage_function
30     Er168Di          168Er_CD8A          CD8A      CD8A           lineage
31     Tm169Di  169Tm_CD159A_NKG2A  CD159A_NKG2A     KLRC1           lineage
32     Er170Di           170Er_CD3           CD3       CD3           lineage
33     Yb171Di    171Yb_GRANZYME_B    GRANZYME_B      GZMB          function
34     Yb172Di     172Yb_CD279_PD1     CD279_PD1     PDCD1          function
35     Yb173Di        173Yb_CD158B        CD158B   KIR2DL3           lineage
36     Yb174Di          174Yb_CD38          CD38      CD38           lineage
37     Lu175Di      175Lu_PERFORIN      PERFORIN      PRF1          function
38     Yb176Di   176Yb_CD127_IL7RA   CD127_IL7RA      IL7R           lineage
39     Pt198Di          198Pt_CD45          CD45      CD45           lineage
40     Bi209Di         209Bi_CD11B         CD11B     ITGAM           lineage

In [46]:
df_tbnk_lineage = df_tbnk[df_tbnk['marker_class'] == 'lineage'].reset_index(drop = True)

In [47]:
df_tbnk_lineage

   fcs_colname            fcs_desc       antigen   Symbol marker_class
0      Cd106Di          106Cd_CD27          CD27     CD27      lineage
1      Cd110Di   110Cd_CD336_NKp44   CD336_NKp44     NCR2      lineage
2      Cd111Di           111Cd_CD4           CD4      CD4      lineage
3      Cd114Di          114Cd_CD70          CD70     CD70      lineage
4      In115Di          115In_CD57          CD57   B3GAT1      lineage
5      Cd116Di  116Cd_CD159C_NKG2C  CD159C_NKG2C    KLRC2      lineage
6      Pr141Di    141Pr_CD196_CCR6    CD196_CCR6     CCR6      lineage
7      Nd142Di   142Nd_CD183_CXCR3   CD183_CXCR3    CXCR3      lineage
8      Nd144Di          144Nd_CD69          CD69     CD69      lineage
9      Nd145Di          145Nd_CD94          CD94    KLRD1      lineage
10     Nd146Di         146Nd_CD161         CD161    KLRB1      lineage
11     Nd148Di          148Nd_CD16          CD16   FCGR3A      lineage
12     Eu153Di   153Eu_CD185_CXCR5   CD185_CXCR5    CXCR5      lineage
13     Sm154Di        154Sm_CD45RO        CD45RO   CD45RO      lineage
14     Gd155Di        155Gd_CD45RA        CD45RA   CD45RA      lineage
15     Tb159Di    159Tb_CD197_CCR7    CD197_CCR7     CCR7      lineage
16     Dy163Di          163Dy_CD56          CD56    NCAM1      lineage
17     Ho165Di          165Ho_CD19          CD19     CD19      lineage
18     Er168Di          168Er_CD8A          CD8A     CD8A      lineage
19     Tm169Di  169Tm_CD159A_NKG2A  CD159A_NKG2A    KLRC1      lineage
20     Er170Di           170Er_CD3           CD3      CD3      lineage
21     Yb173Di        173Yb_CD158B        CD158B  KIR2DL3      lineage
22     Yb174Di          174Yb_CD38          CD38     CD38      lineage
23     Yb176Di   176Yb_CD127_IL7RA   CD127_IL7RA     IL7R      lineage
24     Pt198Di          198Pt_CD45          CD45     CD45      lineage
25     Bi209Di         209Bi_CD11B         CD11B    ITGAM      lineage

## Analysis

In [36]:
# get only common markers between TBNK & MYELOID
df_merged = pd.merge(
    df_tbnk[['antigen', 'marker_class']],
    df_myeloid[['antigen', 'marker_class']],
    on='antigen',
    suffixes=('_tbnk', '_myeloid')
)

In [37]:
df_merged

      antigen marker_class_tbnk marker_class_myeloid
0        CD70           lineage              lineage
1        CD16           lineage              lineage
2  CD274_PDL1          function             function
3        CD45           lineage              lineage

In [38]:
# get only LINEAGE markers
df_merged[df_merged['marker_class_tbnk'] == 'lineage']

  antigen marker_class_tbnk marker_class_myeloid
0    CD70           lineage              lineage
1    CD16           lineage              lineage
3    CD45           lineage              lineage